### ISSUE TITLE
When a flaired user gets unflaired, the new 'unflair' doesn't get saved in the DB

### ISSUE THREAD

**Issue by marcosmarp** [ornato-t/flairchange_bot#1]
This generates repeating the comment on already warned users. See [this](https://www.reddit.com/r/PoliticalCompassMemes/comments/v18wof/comment/iam4neg/?utm_source=share&utm_medium=web2x&context=3) thread for an example.

I believe that this is because your current logic or DB schema only considers updating the flairs array of the user when a new flair appears; maybe you could have an special number/value on the array that means unflaired?

**Comment by ornato-t** [comment]
Thansk for letting me know! Yeah, you kinda nailed the issue. What happens is that the bot doesn't save any data regarding the unflaired. In order to keep the data consistent I didn't code it to save **null** as a flair for users already present in the DB, so at the moment it just gets discarded and never pushed to the database.

I was hoping this to be a rare and unnoticeable corner case but as it turns out it's not. I'll work on this.

**Comment by ornato-t** [comment]
Should be fixed on 562b11f18b50bbbbeef204bce7fba6431f725424

Instead of polluting the flairs array, a boolean flag `unflaired` is added to the DB entry. If a user has said flag it gets treated as an unflaired. If they later get a flair once again the flag is removed.
